### PR TITLE
Adds RequestHandTrackingHints to Ultraleap

### PR DESCRIPTION
**Pull request by bj-rn**
This feature was requested by @ravel_of. See Ultraleap API reference for details:

* https://docs.ultraleap.com/api-reference/tracking-api/group/group___hints.html
* https://docs.ultraleap.com/api-reference/unity-api/class/class_leap_1_1_controller.html?highlight=requesthandtrackinghints#function-Leap.Controller.RequestHandTrackingHints

image
image

### CODE REVIEW

**Comment by joreg** [comment]
thanks for that!

i'd like to suggest to remove these comments from the help patch though:
grafik
copying such large parts of documentation from an external source is not a good idea. that info might change (as is even mentioned in the text). we want to have a single source of truth and that's their website. so next to the hints iobox i'd just put something like: "For more on hints, see: LINK"

for the same reason please also remove the full copy of hint infos in the UltraLeap process node and also inside the Helper.cs. 

then a thought: wouldn't it be enough to apply hints as they change? instead of having two pins (one with the spread of requested hints and another to bang the request). so i'm thinking just a "Requested Hints" input could be enough?

**Comment by bj-rn** [comment]
> i'd like to suggest to remove these comments from the help patch though

I shortened it like so since I think some information in the patch is beneficial:
image

> please also remove the full copy of hint infos in the UltraLeap process node and also inside the Helper.cs.

done

> wouldn't it be enough to apply hints as they change?

Since this is rather low-level / advanced  and this applies: 
_"Send a specific set of hints, if this does not include previously set ones, **they will be cleared**."_
I'd argue that they should only be set explicitly.

**Comment by joreg** [comment]
thanks for the changes. 

but "Send a specific set of hints, if this does not include previously set ones, they will be cleared." this just means that the spread of hints you enter is always exactly what's being requested. i don't think one would expect anything other than this behavior if they input a spread. instead, if you have a bang to request, you'd indeed have to explain that previous requests will be gone. 

another question: is there a way to read which hints are currently requested? i'm wondering if there are certain types of state changes on the server/device that would wipe out the hints and you'd have to know as a user that you'd now have to re-request them.

**Comment by bj-rn** [comment]
> is there a way to read which hints are currently requested?

No there isn't and I also couldn't find out what the standard ones are. So with requesting some you' ll probably "wipe" the stuff that is preset, which is exactly why I think it should only be done explicitly.

"Send a specific set of hints, if this does not include previously set ones, they will be cleared." is a remark taken from the Leap documentation.

**Pull request merged**
